### ISSUE TITLE
programming script for Question & Task UI

### ISSUE THREAD

**Issue by CU1KNIGHT** [CU1KNIGHT/PiratenDerWahrscheinlichkeiten#10]
* script um eine Frage auszuwählen, sodass wenn der Charachter startet eine Frage von der Fragen Datei bekommt.
* script für Antwort auswählen und in einem Datei zu speichern

  -   radio button auswählen
  -  text eingabe
  -  Antworte Speichern in einem Datei
  -  Fragen mit ID bezeichnet 
  -  Antworte in einem CSV Datei Speichern (Frage ID, sollte mit Antwort ID matchen)
z.B. Frage in einem Spalte, richtige Antwort in 2. Spalte und User Antwort in 3. Spalte und spalte für die Frage ID
mit script vergleicht man richtig oder falsch
* script für das Ergebnis für die Fragen

**Comment by CU1KNIGHT** [comment]
@44elvi Ich habe die Mapping angepasst und UI Size gefixt, noch todo ist die Inseln mapping mache ich noch.
wie läuft es mit UI Design integration?

**Comment by 44elvi** [comment]
@CU1KNIGHT perfekt, ich danke dir! was muss noch von UI Designs integriert werden?

**Comment by CU1KNIGHT** [comment]
ich sehe, dass die Fragen noch plain text ( ohne Design integration )hast die [Design ](https://datashare.tu-dresden.de/s/PTKo4Q2nqf9NfXw)von @JiaxiJiang2  integriert?
