### ISSUE TITLE
Design Game Menu UI

### ISSUE THREAD

**Issue by CU1KNIGHT** [CU1KNIGHT/PiratenDerWahrscheinlichkeiten#2]

**Comment by michellelorenz** [comment]
- Informationen sammeln und einen Überblick machen, was in das Menu soll (wichtigste Funktionen bestimmen)
- Layout Entwicklung
- Grafiken, wie Symbole und Buttons erstellen
- Schriftart wählen und kurze Textbeschreibungen verfassen
- Interaktive Elemente designen
- Testen, ist es leicht hindurch zu navigieren? (nachdem Matti es implementiert hat)
