### ISSUE TITLE
write Game Problems and Questions

### ISSUE THREAD

**Issue by CU1KNIGHT** [CU1KNIGHT/PiratenDerWahrscheinlichkeiten#3]
* Definitionen für die Wahrscheinlichkeiten
* lückentext für die Defnintionen
* Aufgaben für die Rechnungen

**Comment by CU1KNIGHT** [comment]
@44elvi  ich habe die Erkläreungen unter [Basics ](https://github.com/CU1KNIGHT/PiratenDerWahrscheinlichkeiten/tree/main/resources/Game-Task-and-Questions/basics)Ordner 
und die Aufgaben under [Tasks ](https://github.com/CU1KNIGHT/PiratenDerWahrscheinlichkeiten/tree/main/resources/Game-Task-and-Questions/Tasks)Ordner

**Comment by CU1KNIGHT** [comment]
@44elvi kannst du bitte review machen, schaue bitte mal an, ob die Dateien in Ordnung sind, und ob du mehr fragen und Aufgaben brauchst oder ob ich was  in der CSV ändern soll.

**Comment by 44elvi** [comment]
1. Vielleicht sinnvoller zu überlegen welche Aufgaben/Fragen zu welcher Insel gehören; je nach Komplexität, und die dann in verschiedene csv Files zu verteilen? 
2. Werden alle Fragen in alle Inseln Alternative-Antworten enthalten? 

Ansonsten gutes Model 😊

**Comment by CU1KNIGHT** [comment]
Zu 1. In CSV Q1 du kannst sehen in ersten Spalten Thema Grundlage-wahrscheinlichkeiten
Und das ist ein Insel so zu Sagen

**Comment by CU1KNIGHT** [comment]
Zu 2. Die Grundlagen Inseln ja für schwieriger Insel nein, Spieler soll ganaue Antwort eingeben

**Comment by 44elvi** [comment]
1. Kannst du bitte aber zumindest Inseln nr. dazu eingeben? Es gibt 5 verschiedene subjects und 3 Inseln.

zu 2. Dann bitte genauer definieren und in einem anderen csv hinzufügen(wo nur eine richtige Antwort steht). Weil das script sieht anders aus, wenn es alternativen geben soll und wenn eine richtige Antwort.
