### ISSUE TITLE
programming script for Game Charachter

### ISSUE THREAD

**Issue by CU1KNIGHT** [CU1KNIGHT/PiratenDerWahrscheinlichkeiten#5]

**Comment by 44elvi** [comment]
1. Scripts to control the character's behaviour. Handle input from the player, apply forces for movement, and trigger animations based on the character's state.

2. Implement Game Mechanics:
Implement various game mechanics related to the character. 

3. Testing and Iteration:
Test your character thoroughly to ensure it behaves as expected.
