### ISSUE TITLE
Design Game UI theme

### ISSUE THREAD

**Issue by CU1KNIGHT** [CU1KNIGHT/PiratenDerWahrscheinlichkeiten#7]
Farben definieren (richtig, Falsch ,Hinweis, Aufgabe, Antwort),
Font auswählen
icons für texte wie info ℹ️  richtig ✅  falsch ❌
ein Datei für Style im Spiel schreiben, wo Farben, Font für das Spiel definiert ist

**Comment by michellelorenz** [comment]
Background is already designed (wave pattern in next cloud)
in ui design is already a "go-back" button (nextcloud)

**Comment by CU1KNIGHT** [comment]
@michellelorenz Ich habe die beschreibung angepasst, es geht hier um icons, Farben und Fonts
